# title: Just the Docs Template
# description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs

# url: https://daianeklein.github.io/data-and-tech-notes

# plugins:
#   - jekyll-default-layout




title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://daianeklein.github.io/data-and-tech-notes

plugins:
  - jekyll-default-layout

# Enable ordered navigation
nav_order: 1

# Sidebar navigation structure
nav_sort: case_insensitive

